/*
 * GENERATED FILE. DO NOT EDIT.
 *
 * Generated by:
 *   python3 tools/generate_poc_artifacts.py
 *
 * Inputs:
 *   orbitfabric_models/mission/
 *   orbitfabric_models/poc_slice.yaml
 *
 * This file is contract-only.
 * It contains no runtime logic, no PUS framing, no transport,
 * no scheduling and no dynamic allocation.
 */

#ifndef OF_MISSION_CONTRACT_H
#define OF_MISSION_CONTRACT_H

#include <stdint.h>

#define OF_CONTRACT_NAME "poc_vertical_slice"
#define OF_CONTRACT_VERSION "0.1-poc"

typedef enum {
    OF_TM_INVALID = 0,
    OF_TM_OBC_BUS_VOLTAGE_MV = 0x4001
} of_tm_id_t;

typedef enum {
    OF_CMD_INVALID = 0,
    OF_CMD_PING = 0x1701
} of_cmd_id_t;

typedef enum {
    OF_EVENT_INVALID = 0,
    OF_EVENT_VOLTAGE_OUT_OF_BOUNDS = 0x5001
} of_event_id_t;

typedef enum {
    OF_HK_SET_INVALID = 0,
    OF_HK_SET_OBC = 0x0001
} of_hk_set_id_t;

#define OF_HK_SET_OBC_COLLECTION_INTERVAL_S 1u

typedef struct {
    uint16_t obc_bus_voltage_mv;
} of_hk_obc_t;

#endif /* OF_MISSION_CONTRACT_H */
