from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .resolver import RESOLVED_PROJECTION_KIND, RESOLVED_PROJECTION_VERSION


class FlightContractError(RuntimeError):
    pass


def load_resolved_projection(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise FlightContractError(f"cannot read resolved projection {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise FlightContractError("resolved projection must be a JSON object")
    return value


def render_flight_contract(resolved: dict[str, Any]) -> str:
    """Render mission_contract.h from adapter-owned resolved projection IR only."""
    _validate_resolved_identity(resolved)
    settings = _mapping(resolved, "settings")
    flight = _mapping(settings, "flight_contract")
    contract_name = _string(flight, "contract_name")
    contract_version = _string(flight, "contract_version")

    projections = resolved.get("projections")
    if not isinstance(projections, list):
        raise FlightContractError("resolved projections must be an array")

    by_kind: dict[str, list[dict[str, Any]]] = {
        "telemetry_parameter": [],
        "command": [],
        "event": [],
        "housekeeping_packet": [],
    }
    for projection in projections:
        if not isinstance(projection, dict):
            raise FlightContractError("resolved projection entry must be an object")
        kind = projection.get("kind")
        if kind not in by_kind:
            raise FlightContractError(f"unsupported resolved projection kind: {kind}")
        by_kind[kind].append(projection)

    for values in by_kind.values():
        values.sort(key=lambda item: _string(item, "binding_id"))

    lines = [
        "/*",
        " * GENERATED FILE. DO NOT EDIT.",
        " *",
        " * Generated by the OrbitFabric OpenOBSW/OpenSVF reference adapter.",
        " * Input: adapter-owned Resolved Projection Model.",
        " *",
        " * This file is contract-only.",
        " * It contains no runtime logic, no PUS framing, no transport,",
        " * no scheduling and no dynamic allocation.",
        " */",
        "",
        "#ifndef OF_MISSION_CONTRACT_H",
        "#define OF_MISSION_CONTRACT_H",
        "",
        "#include <stdint.h>",
        "",
        f'#define OF_CONTRACT_NAME "{_escape_c_string(contract_name)}"',
        f'#define OF_CONTRACT_VERSION "{_escape_c_string(contract_version)}"',
        "",
    ]

    _render_enum(
        lines,
        "OF_TM_INVALID",
        "of_tm_id_t",
        by_kind["telemetry_parameter"],
        "numeric_id",
    )
    _render_enum(lines, "OF_CMD_INVALID", "of_cmd_id_t", by_kind["command"], "numeric_id")
    _render_enum(lines, "OF_EVENT_INVALID", "of_event_id_t", by_kind["event"], "numeric_id")
    _render_enum(
        lines,
        "OF_HK_SET_INVALID",
        "of_hk_set_id_t",
        by_kind["housekeeping_packet"],
        "sid",
    )

    for projection in by_kind["housekeeping_packet"]:
        target = _mapping(projection, "target")
        symbol = _string(target, "c_symbol")
        interval = _positive_int(target, "collection_interval_s")
        lines.append(f"#define {symbol}_COLLECTION_INTERVAL_S {interval}u")
    if by_kind["housekeeping_packet"]:
        lines.append("")

    for projection in by_kind["housekeeping_packet"]:
        target = _mapping(projection, "target")
        struct_type = _string(target, "struct_type")
        members = target.get("members")
        if not isinstance(members, list) or not members:
            raise FlightContractError(
                f"housekeeping projection {_string(projection, 'binding_id')} has no resolved members"
            )
        lines.append("typedef struct {")
        for member in members:
            if not isinstance(member, dict):
                raise FlightContractError("resolved housekeeping member must be an object")
            c_type = _string(member, "c_type")
            field_name = _string(member, "field_name")
            lines.append(f"    {c_type} {field_name};")
        lines.append(f"}} {struct_type};")
        lines.append("")

    lines.extend(["#endif /* OF_MISSION_CONTRACT_H */", ""])
    return "\n".join(lines)


def write_flight_contract(resolved: dict[str, Any], output_file: Path) -> Path:
    content = render_flight_contract(resolved)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8", newline="\n")
    return output_file


def materialize_flight_contract(resolved_projection_file: Path, output_file: Path) -> Path:
    return write_flight_contract(load_resolved_projection(resolved_projection_file), output_file)


def _validate_resolved_identity(resolved: dict[str, Any]) -> None:
    if resolved.get("kind") != RESOLVED_PROJECTION_KIND:
        raise FlightContractError("unexpected resolved projection kind")
    if resolved.get("resolved_projection_version") != RESOLVED_PROJECTION_VERSION:
        raise FlightContractError("unsupported resolved projection version")


def _render_enum(
    lines: list[str],
    invalid_symbol: str,
    type_name: str,
    projections: list[dict[str, Any]],
    value_property: str,
) -> None:
    lines.extend(["typedef enum {", f"    {invalid_symbol} = 0,"])
    for index, projection in enumerate(projections):
        target = _mapping(projection, "target")
        symbol = _string(target, "c_symbol")
        value = _positive_int(target, value_property)
        comma = "," if index < len(projections) - 1 else ""
        lines.append(f"    {symbol} = 0x{value:04X}{comma}")
    lines.extend([f"}} {type_name};", ""])


def _mapping(parent: dict[str, Any], key: str) -> dict[str, Any]:
    value = parent.get(key)
    if not isinstance(value, dict):
        raise FlightContractError(f"resolved property {key} must be an object")
    return value


def _string(parent: dict[str, Any], key: str) -> str:
    value = parent.get(key)
    if not isinstance(value, str) or not value:
        raise FlightContractError(f"resolved property {key} must be a non-empty string")
    return value


def _positive_int(parent: dict[str, Any], key: str) -> int:
    value = parent.get(key)
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise FlightContractError(f"resolved property {key} must be a positive integer")
    return value


def _escape_c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
