from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .resolver import RESOLVED_PROJECTION_KIND, RESOLVED_PROJECTION_VERSION


class OpenSvfSrdbError(RuntimeError):
    pass


def load_resolved_projection(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise OpenSvfSrdbError(f"cannot read resolved projection {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise OpenSvfSrdbError("resolved projection must be a JSON object")
    return value


def render_opensvf_srdb(resolved: dict[str, Any]) -> str:
    """Render OpenSVF-native SRDB YAML from resolved projection IR only."""
    if resolved.get("kind") != RESOLVED_PROJECTION_KIND:
        raise OpenSvfSrdbError("unexpected resolved projection kind")
    if resolved.get("resolved_projection_version") != RESOLVED_PROJECTION_VERSION:
        raise OpenSvfSrdbError("unsupported resolved projection version")

    projections = resolved.get("projections")
    if not isinstance(projections, list):
        raise OpenSvfSrdbError("resolved projections must be an array")
    telemetry = [
        item
        for item in projections
        if isinstance(item, dict) and item.get("kind") == "telemetry_parameter"
    ]
    telemetry.sort(key=lambda item: _target_string(item, "srdb_name"))

    lines = [
        "# GENERATED FILE. DO NOT EDIT.",
        "#",
        "# Generated by the OrbitFabric OpenOBSW/OpenSVF reference adapter.",
        "# Input: adapter-owned Resolved Projection Model.",
        "#",
        "# OpenSVF-native SRDB artifact.",
        "",
        "parameters:",
    ]

    for projection in telemetry:
        target = _mapping(projection, "target")
        opensvf = _mapping(target, "opensvf")
        semantic_container = _mapping(projection, "core_semantics")
        semantic = _mapping(semantic_container, "source")
        name = _string(target, "srdb_name")
        description = _string(semantic, "description")
        unit = _string(semantic, "unit")
        dtype = _string(opensvf, "dtype")
        classification = _string(opensvf, "classification")
        domain = _string(opensvf, "domain")
        model_id = _string(opensvf, "model_id")
        valid_range = opensvf.get("valid_range")
        if (
            not isinstance(valid_range, list)
            or len(valid_range) != 2
            or not all(isinstance(value, (int, float)) for value in valid_range)
        ):
            raise OpenSvfSrdbError("resolved OpenSVF valid_range must contain two numbers")
        pus = _mapping(opensvf, "pus")
        apid = _non_negative_int(pus, "apid")
        service = _non_negative_int(pus, "service")
        subservice = _non_negative_int(pus, "subservice")
        parameter_id = _positive_int(pus, "parameter_id")

        lines.extend(
            [
                f"  {name}:",
                f"    description: {_yaml_string(description)}",
                f"    unit: {_yaml_string(unit)}",
                f"    dtype: {dtype}",
                f"    classification: {classification}",
                f"    domain: {domain}",
                f"    model_id: {model_id}",
                f"    valid_range: [{float(valid_range[0]):.1f}, {float(valid_range[1]):.1f}]",
                "    pus:",
                f"      apid: 0x{apid:X}",
                f"      service: {service}",
                f"      subservice: {subservice}",
                f"      parameter_id: 0x{parameter_id:X}",
            ]
        )

    lines.append("")
    return "\n".join(lines)


def write_opensvf_srdb(resolved: dict[str, Any], output_file: Path) -> Path:
    content = render_opensvf_srdb(resolved)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8", newline="\n")
    return output_file


def materialize_opensvf_srdb(resolved_projection_file: Path, output_file: Path) -> Path:
    return write_opensvf_srdb(load_resolved_projection(resolved_projection_file), output_file)


def _mapping(parent: dict[str, Any], key: str) -> dict[str, Any]:
    value = parent.get(key)
    if not isinstance(value, dict):
        raise OpenSvfSrdbError(f"resolved property {key} must be an object")
    return value


def _string(parent: dict[str, Any], key: str) -> str:
    value = parent.get(key)
    if not isinstance(value, str) or not value:
        raise OpenSvfSrdbError(f"resolved property {key} must be a non-empty string")
    return value


def _target_string(projection: dict[str, Any], key: str) -> str:
    return _string(_mapping(projection, "target"), key)


def _non_negative_int(parent: dict[str, Any], key: str) -> int:
    value = parent.get(key)
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise OpenSvfSrdbError(f"resolved property {key} must be a non-negative integer")
    return value


def _positive_int(parent: dict[str, Any], key: str) -> int:
    value = _non_negative_int(parent, key)
    if value == 0:
        raise OpenSvfSrdbError(f"resolved property {key} must be positive")
    return value


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
